name: CI
on:
  pull_request:
    branches:
      development

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@v1
      - name: Install dependencies for all packages
        run: melos build:pub_get:all
      - name: Test all packages
        run: ../../scripts/test_all.sh