name: CI
on:
  pull_request:
    branches:
      main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_android:
    name: Build Flutter Android(appbundle)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle
  
